package(default_visibility = ["//visibility:public"])

exports_files(["*.bzl"])

# Scala Native toolchain type
toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

